ec-europa/ec_europa

templates/menu_tree/menu_tree.js, templates/status_messages/status_messages.js, templates/table/table.component.inc, templates/table/table.js
Update the 'table' component.
- Changed: Update the 'table' template.
```sh
no commands
```
=> NEPT-1136: Implements the table component.

package.json, templates/page/page--splash.tpl.php, templates/page/page.component.inc, templates/splash/splash.component.inc, templates/splash/splash.tpl.php
Add a variable on the component splash.
- changed: customize the splash component.
- changed: customize the splash page.
```sh
drush cc all
```
=> NEPT-1096: Add the component splash.

templates/form_element/form-element--checkbox.tpl.php, templates/menu_link/menu_link.component.inc, templates/menu_tree/menu-tree--user-menu.tpl.php, templates/menu_tree/menu_tree.component.inc, templates/site_header/site-header.tpl.php, templates/site_header/site_header.component.inc, templates/site_switcher/site-switcher.tpl.php, templates/site_switcher/site_switcher.component.inc
=> NEPT-1145: Implements the user-menu in site-switcher component.

composer.json, package.json
Update the version 0.0.4.
- Updated: The version number to 0.0.4.
```sh
no commands
```
=> NEPT-1577: Update the version 0.0.4.

templates/block/block--sidebar-first--views.tpl.php, templates/link_blocks/link-blocks.tpl.php, templates/link_blocks/link_blocks.component.inc
Add new component link_blocks to use in the members list in community feature
- Added:  Added link_blocks component
=> NEPT-1189: Theme the member list inside the community feature.

.travis.yml, templates/container/container--file--wysiwyg.tpl.php, templates/file/file--audio--wysiwyg.tpl.php, templates/file/file--document--wysiwyg.tpl.php, templates/file/file--image--wysiwyg.tpl.php, templates/file/file--video--wysiwyg.tpl.php
Insert wysiwyg templates for file entity and file container in order to remove the unwanted "div" container appearing around any files inserted in a WYSIWYG field like "body".
- Added: templates/container/container--file--wysiwyg.tpl.php
- Added: templates/file/file--audio--wysiwyg.tpl.php
- Added: templates/file/file--document--wysiwyg.tpl.php
- Added: templates/file/file--image--wysiwyg.tpl.php
- Added: templates/file/file--video--wysiwyg.tpl.php
drush cc all
=> NEPT-2038: Add wysiwyg templates for file entity and file container

templates/easy_breadcrumb/easy_breadcrumb.component.inc, templates/page_header/page_header.component.inc
Upgrade easy breadcrumb module to v.2.15. Adapt themes to the upgrade.
- Changed: 
- templates/easy_breadcrumb/easy_breadcrumb.component.inc
- templates/page_header/page_header.component.inc
=> NEPT-1315: Upgrade easy breadcrumb module to the latest version

.gitignore
Fix #81 Followup add a missing file on gitignore.
=> Issue #81: Update gitignore file.

templates/form_element/form-element--checkbox.tpl.php
=> Issue #78: Add missing description in form element checkbox.

templates/status_messages/status-messages.tpl.php, templates/status_messages/status_messages.component.inc
=> Issue #84: Fix status messages component.

composer.json
=> Issue #92: Update composer configuration.

templates/form_element/form-element--checkbox.tpl.php, templates/form_element/form-element--radio.tpl.php, templates/form_element/form-element.tpl.php
=> Issue #88: Fix form_element component.

templates/site_header/site-header.tpl.php, templates/site_header/site_header.component.inc, templates/site_slogan/site_slogan.component.inc
Add the site slogan to the page header, there is no ecl for this component.
=> NEPT-1419: Site slogan component no longer shows

templates/pager/pager.component.inc
=> Issue #103: Remove the pager definition hook as it has been included in Atomium

templates/form_element/form-element--checkbox.tpl.php, templates/form_element/form-element--radio.tpl.php
Fix #108 
Related to NEMA-2329, NEPT-2383
=> Issue #108: Update and fix descriptions.

templates/easy_breadcrumb/easy_breadcrumb.component.inc
=> Issue #116: Fix easy_breadcrumb component.

templates/easy_breadcrumb/easy_breadcrumb.component.inc
=> Issue #116: Optimize easy_breadcrumb by removing render calls from template

sass/style.scss, templates/easy_breadcrumb/easy-breadcrumb.tpl.php, templates/easy_breadcrumb/easy_breadcrumb.component.inc
=> Issue #116: Breadcrumb component update

templates/field/field.component.inc, templates/field/field.tpl.php, templates/item_list/item-list--field.tpl.php
=> Issue #128: Field component update.

templates/menu_link/menu_link.component.inc
=> Issue #132: Fix menu link to properly display Login/logout link as ECL.

README.md
=> Issue #110: Update documentation master.

.drone.yml, README.md, composer.json, taskman.yml.dist, templates/comment/comment.tpl.php, templates/ds/ds-1col-wrapper.tpl.php, templates/ds/ds-1col.tpl.php, templates/ds/ds-2col-stacked-fluid.tpl.php, templates/ds/ds-2col.tpl.php, templates/ds/ds-3col-equal-width.tpl.php, templates/ds/ds-3col-stacked-equal-width.tpl.php, templates/ds/ds-3col-stacked-fluid.tpl.php, templates/ds/ds-3col-stacked.tpl.php, templates/ds/ds-3col.tpl.php, templates/ds/ds-4col.tpl.php, templates/html/html.tpl.php, templates/maintenance_page/maintenance-page--offline.tpl.php, templates/maintenance_page/maintenance-page.tpl.php, templates/pager/pager.component.inc, templates/views_view_table/views-view-table.tpl.php
=> Issue #137: Use Taskman

composer.json, templates/easy_breadcrumb/easy_breadcrumb.component.inc, templates/page_header/page_header.component.inc
=> Issue #150: Revert "NEPT-1315: Adapt ec_europa theme to the new version of easy-breadcrumb module.

templates/item_list/item-list--status-messages.tpl.php, templates/status_messages/status_messages.component.inc
=> Issue #153: Fix components.

composer.json, templates/ds/ds-2col-stacked-fluid.tpl.php, templates/link/link.component.inc, templates/pager/pager.component.inc, templates/pager_current/pager-current.tpl.php, templates/pager_next/pager_next.component.inc, templates/pager_previous/pager_previous.component.inc
=> Update atomium v. 2.28 and update pager accordingly.

composer.json, template.php, templates/checkboxes/checkboxes.component.inc, templates/pager/pager.component.inc, templates/password/password.component.inc, templates/radios/radios.component.inc, templates/select/select.component.inc, templates/textfield/textfield.component.inc, templates/views_view_grid/views_view_grid.component.inc
=> 159 update drupal convention 0.0.x

composer.json
=> Issue #181: Composer package updated phptaskman/changelog 0.2.3 -> 0.2.4

templates/textarea/textarea.component.inc
**Description:**
Remove duplication of field properties on textarea fields.
Changed:  textarea.component.inc
=> NEPT-2740: Remove duplication of properties

assets/scripts/init.js, templates/html/html.component.inc, templates/menu_tree/menu_tree.js
=> NEPT-2110: Responsive menu should not be expanded by default

templates/form_element/form_element.component.inc
Fixing issue https://github.com/ec-europa/ec_europa/issues/198.
=> NEPT-2489: Fix issues/198.

templates/textarea/textarea.component.inc, templates/textarea/textarea.css
NEPT-2755
Fix missing textarea error highlight
=> NEPT-2755: Fix textarea error highlight

templates/menu_tree/menu_tree.js
this branch is based on 0.0.14.1 but can be merged into 0.0.x if it passes review and can be used for a 0.0.14.2 hotfix if needed.
=> NEPT-2781: Make burger menu work with megamenu.

template.php
Fix fatal error on some conditions using nexteuropa_dgt_connector
=> NEPT-2815: Fix function nesting.
